dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://172.16.32.77:2181
  protocol:
    name: dubbo
    serialization: hessian2
    port: 20880
  provider:
    timeout: 1000
server:
  port: 9091
spring:
  application:
    name: dubbo-provider